AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  APK distribution allows developers to add download channel information to their Android app installation packages (APKs). This channel data can then be used for attribution and analytics purposes. 
Parameters:
  S3BucketName:
    Type: String
    MinLength: '3'
    MaxLength: '63'
  APPKey:
    Type: String
    Default: ''
Metadata:
  AWS::ServerlessRepo::Application:
    Name: apk-distribution
    Description: >
      apk-distribution
      
      APK distribution allows developers to add download channel information to their Android app installation packages (APKs). This channel data can then be used for attribution and analytics purposes.
    Author: Huang Jidong
    SpdxLicenseId: MIT-0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['s3', 'cloudfront', 'lambda', 'distribution', 'apk']
    HomePageUrl: https://github.com/turmind/apk-distribution
    SemanticVersion: 1.1.1
    SourceCodeUrl: https://github.com/turmind/apk-distribution
Resources:
  s3APKTmpBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/apk-distribution.zip
      Handler: distribution.Handler::handleRequest
      Runtime: java11
      Description: Java function
      Environment:
        Variables:
          BUCKET: !Ref S3BucketName
          TMPBUCKET: !Ref s3APKTmpBucket
          APPKEY: !Ref APPKey
          REGION: !Ref AWS::Region
      MemorySize: 2048
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AmazonS3FullAccess
      Layers:
        - !Ref libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: apk-distribution-lib
      Description: Dependencies for the apk-distribution app.
      ContentUri: build/apk-distribution-lib.zip
      CompatibleRuntimes:
        - java11
  apkDistributionApiGateWay:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: apk-distribution Proxy
      Description: Lambda proxy use for apk-distribution
      ProtocolType: HTTP
      Target: !GetAtt function.Arn
  apiGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt function.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${apkDistributionApiGateWay}/*
  CloudFrontOriginIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: origin identity
  BucketPolicy:
    DependsOn: CloudFrontOriginIdentity
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref s3APKTmpBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginIdentity}
            Action: s3:GetObject
            Resource: !Sub arn:aws:s3:::${s3APKTmpBucket}/*
  publicDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub ${s3APKTmpBucket}.s3.${AWS::Region}.amazonaws.com
            Id: tmp-apk-bucket-access
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginIdentity}
          - DomainName: !Sub ${apkDistributionApiGateWay}.execute-api.${AWS::Region}.amazonaws.com
            Id: apk-distribution-access
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        Enabled: true
        Comment: apk distribution
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: tmp-apk-bucket-access
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          ViewerProtocolPolicy: redirect-to-https
        CacheBehaviors:
          - AllowedMethods:
              - GET
              - HEAD
            TargetOriginId: apk-distribution-access
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            OriginRequestPolicyId: 775133bc-15f2-49f9-abea-afb2e0bf67d2
            ViewerProtocolPolicy: redirect-to-https
            PathPattern: /
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
Outputs:
  CDNDomain:
    Description: cdn access url
    Value: !GetAtt publicDistribution.DomainName